name: Lint nextflow pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NXF_VER: "24.10.6"
  NXF_WORK: ${{ github.workspace }}/work

defaults:
      run:
        shell: bash -el {0}

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install nf-core
      - name: Run lint
        run: |
          nf-core pipelines schema lint nextflow_schema.json
